name: Build Website
on: "push" 
jobs:
  website:
    name: Run Tests
    runs-on: ubuntu-latest
    container: mjkli/react-vite
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install deps
        run: npm i
      
      - name: Run Unit Tests
        run: npx vitest run --coverage
      
      - name: Run Build
        run: npm run build
      
      - name: Compress build
        run: tar -czvf pww.tar.gz dist/ 
      
      - name: Uploading Build
        uses: actions/upload-artifact@v4
        with:
          name: pww-build
          path: pww.tar.gz

  
  infrastructure:
    name: Verify Infrastructure
    runs-on: ubuntu-latest
    container: mjkli/terraform-aws:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-west-1"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Terraform init
        run: terraform init
        working-directory: tf-infra

      - name: Terraform validate
        run: terraform validate
        id: validate
        working-directory: tf-infra

      - name: Terraform validate status
        if: steps.validate.outcome == 'falure'
        run: exit 1

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        working-directory: tf-infra

      - name: Terraform plan status
        if: steps.plan.outcome == 'falure'
        run: exit 1
      
      - name: Terraform apply
        working-directory: tf-infra
        run: terraform apply -auto-approve -input=false
  
  Upload:
    name: Upload to s3 bucket
    runs-on: ubuntu-latest
    container: mjkli/terraform-aws:latest
    needs: ["website", "infrastructure"]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-west-1"
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: pww-build
      
      - name: unzip build
        run: tar -xzvf pww-build.zip -C dist/
      
      - name: Upload to s3 bucket
        run: aws s3 sync dist/ s3://pww-mjkli-bucket